### ISSUE TITLE
Source for Johns Hopkins, Stanford, etc projections at the county level?

### ISSUE THREAD

**Issue by benisonp** [StateOfCalifornia/CalCAT#24]
There is some code that contains helpful links to repos that contain the data used in visualization, but some are missing. Would anyone be able to point to where they are; e.g. Johns Hopkins, LEMMA, Stanford? Alternatively, having a source for the original data would be great. Thanks!

**Comment by vargoCDPH** [comment]
The model results for Stanford and JHU have been provided to the state directly, rather than scraped from public sites, which is why they do not appear in this public version of CalCAT. LEMMA is a relatively recent edition. We are working to get this into the repository; however the data is only available for California. The [data](https://github.com/LocalEpi/LEMMA-Forecasts/tree/master/Forecasts) and [documentation](https://localepi.github.io/LEMMA/index.html) for LEMMA can be found online.
